spring:
  profiles:
    active: local
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: admin
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456
